# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Messenger' do
  use_frameworks!

pod 'Firebase/Core'
pod 'Firebase/Auth'
pod 'Firebase/Database'

# Facebook Log In
pod 'FBSDKLoginKit'

# Google Log In
pod 'GoogleSignIn', '5.0.0'

# User Interface
pod 'MessageKit'
pod 'JGProgressHUD'

# Databse for saving info on the device
pod 'RealmSwift'

# Bringing images from web
pod 'SDWebImage'

end
